#!/bin/bash

battery_warned=0
battery_warn_level=10

function getstatus()
{
	date=$(date "+%d/%m/%y %H:%M")
	battery=$(cat /sys/class/power_supply/BAT1/capacity)
	if [ $battery -lt $battery_warn_level ]
	then
		if [ $battery_warned -eq 0 ]
		then
			notify-send -u critical "low battery!"
			battery_warned=1
		fi
	fi

	batteryState=$(cat /sys/class/power_supply/BAT1/status)

	network=$(nmcli -t -f active,ssid dev wifi | grep -m 1 'yes' | cut -d':' -f2)

	networkIcon=
	if [ -n "$network" ]
	then
		networkIcon=
	else
		networkIcon=
	fi


	if [ $(getmuted) = "yes" ]
	then
		volume="mute"
	else
		volume=$(getvolume)
	fi

	batteryIcon=

	if [ "$batteryState" == "Charging" ]
	then
		batteryIcon=
	elif ((battery <= 15))
	then
		batteryIcon=
	elif ((battery >= 16 && battery <= 30))
	then
		batteryIcon=
	elif ((battery >= 31 && battery <= 59))
	then
		batteryIcon=
	elif ((battery >= 60 && battery <= 80))
	then
		batteryIcon=
	elif ((battery >= 81 && battery <= 100))
	then
		batteryIcon=i
	fi

	statusBar="$date | $batteryIcon $battery% | 🔊 $volume | $networkIcon $network"


	echo " "$statusBar" "
	return $battery_warned

}
while true
do
	status=$(getstatus)
	battery_warned=$?
	xsetroot -name "$status"
	sleep 1
done
