#!/bin/bash
date=$(date "+%d/%m/%y %H:%M")
battery=$(cat /sys/class/power_supply/BAT1/capacity)
batteryState=$(echo " - "$(cat /sys/class/power_supply/BAT1/status) | grep "Charging")
network=$(nmcli -t -f active,ssid dev wifi | grep -m 1 'yes' | cut -d':' -f2)
statusBar=$date" | 🔋 "$battery"%"$batteryState

if [ -n "$network" ]
then
	statusBar=$statusBar" | 🖧 "$network
fi
echo " "$statusBar" "
